import Head from 'next/head';
import React from 'react';
import Footer from './Footer';
import Navbar from './Navbar';

const Layout = ({ title, children }) => {
  return (
    <>
      <Head>
        <title> {title ? title + '-Ecommerce' : 'Ecommerce'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between min-h-screen ">
        <header>
          <Navbar />
        </header>
        <main className="container m-auto mt-4 px-6">{children}</main>
        <footer>
          <Footer />
        </footer>
      </div>
    </>
  );
};

export default Layout;
